プレーヤーの角度及び弾丸の反射関係の調整
PandD-Aizu/Minge2021Winter_Team3 pull request #52
Opened 2021-12-17 07:15 UTC by id-isymhrk

## Issue 番号
Close #50 

## 変更内容

1. プレーヤーの角度関係の変化に伴って回転制限を調節しました
2. 弾丸の反射がおかしなことになっていたので、一部修正しました
3. ２に伴って、弾丸が削除される座標を少し広めに設けました

2021-12-17 07:41 UTC, suzakutakumi requested changes
コメント文の部分を削除してください

2021-12-17 08:10 UTC, id-isymhrk commented
コメント文を削除したのでもう一度確認をおねがいします。

2021-12-17 10:41 UTC, matumoto1234 reviewed
宗教

2021-12-17 10:41 UTC, matumoto1234 commented on VirusBuster/src/BulletTemplate.cpp
>  	bool flg = false;
`flg`って名前があいまいなので、`removed` とかにした方がいいかも...?

2021-12-17 10:41 UTC, matumoto1234 commented on VirusBuster/src/BulletTemplate.cpp
>  		flg = true;
これって、y軸に関しては `rm_area` を適用させないでよきなのでしょうか？

2021-12-17 10:41 UTC, matumoto1234 commented on VirusBuster/src/BulletTemplate.cpp
>  		flg = true;
あと、`rm_area` って名前があいまいなので、`expand_rm_area` とかの方がいいかも（宗教）

2021-12-17 10:41 UTC, matumoto1234 commented on VirusBuster/src/BulletTemplate.cpp
>  		flg = true;
あと、こういうのは `is_inside(x, y, w, h)` みたいな関数を用意してそれを使うといいと思います（宗教）

2021-12-17 10:41 UTC, matumoto1234 commented on VirusBuster/src/Player.cpp
> +			angle = (-1) * Math::Pi;
```suggestion
		if (angle < -Math::Pi)
			angle = -Math::Pi;
```

2021-12-17 12:19 UTC, id-isymhrk commented on VirusBuster/src/BulletTemplate.cpp
>  		flg = true;
> これって、y軸に関しては `rm_area` を適用させないでよきなのでしょうか？

ｙ軸は反射しないので現状大丈夫です

2021-12-17 12:20 UTC, id-isymhrk commented
ｙ軸反射の機能をコメントで残しておきました
コメントが２つなのは許してください

2021-12-17 12:22 UTC, id-isymhrk commented on VirusBuster/src/BulletTemplate.cpp
>  	bool flg = false;
@suzakutakumi の記述部分ですが、本人が「大丈夫」と言っていたので修正しておきます

2021-12-17 12:27 UTC, id-isymhrk commented on VirusBuster/src/BulletTemplate.cpp
>  		flg = true;
> あと、こういうのは `is_inside(x, y, w, h)` みたいな関数を用意してそれを使うといいと思います（宗教）

それ作るとしたらBasic.hpp内がいいと思うんですけどどうでしょうか

2021-12-17 12:34 UTC, id-isymhrk commented
ごめんなさい使い終わった変なブランチ使ってました

2021-12-18 12:29 UTC, id-isymhrk commented
inside関数以外はやっておきました。
報告遅れましたが確認お願いします。

2021-12-19 09:37 UTC, suzakutakumi approved these changes
LGTM

2021-12-19 09:38 UTC, merged