Feature/#43/create bullet reflect
PandD-Aizu/Minge2021Winter_Team3 pull request #61
Opened 2021-12-22 11:56 UTC by id-isymhrk

## Issue 番号
#43 

## 変更内容
反射する弾丸を追加しました。
それに伴って既存の弾丸のステータスを調整しました。

2021-12-22 11:59 UTC, id-isymhrk commented
前回のプルリクエストを確認した後にこっちの確認をお願いします。

2021-12-23 01:23 UTC, suzakutakumi requested changes
コメントした部分の修正or議論をしましょう。
また #60 の内容も反映されていますので、以後別にするよう気を付けてください。

2021-12-23 01:23 UTC, suzakutakumi commented on VirusBuster/src/BulletReflect.cpp
> +	static constexpr float speed = 4;
constexpr使うなら、staticいらないのでは?
```suggestion
	constexpr float speed = 4;
```

2021-12-23 01:23 UTC, suzakutakumi commented on VirusBuster/src/BulletReflect.cpp
> +	if (0 >= Body.x or Body.x >= Scene::Width()) {
is_inside_xとis_inside_yを作るのはどうですか?

2021-12-23 02:15 UTC, id-isymhrk commented
> また #60 の内容も反映されていますので、以後別にするよう気を付けてください。
#60 の内容までプッシュされてしまうのは想定外でしたすみません。
ただ一応前述していましたが、今回は前回の変更ありきでした。
もしまたそのような状況だった場合、前回のプルリクエストを削除して今回のものだけ残すべきでしょうか？
変更内容が雑多になってしまうのを防ぐ意味で今回のような対応をとったのですが、おそらく今後もこういった事態になるかもしれないので確認させてください。

2021-12-23 02:23 UTC, id-isymhrk commented on VirusBuster/src/BulletReflect.cpp
> +	static constexpr float speed = 4;
一応[違い](https://www.webdevqa.jp.net/ja/c%2B%2B/%E3%81%84%E3%81%A4%E3%80%81%E3%81%AA%E3%81%9Cconstexpr%E3%81%A7static%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%81%AE%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F/1049279948/)はあるっぽいのですが、なんだか難しい話なので問題ないと思います。
実際、constexprに変えようと思って怠けただけのミスなので異論はありません。

2021-12-23 02:30 UTC, id-isymhrk commented on VirusBuster/src/BulletReflect.cpp
> +	if (0 >= Body.x or Body.x >= Scene::Width()) {
良い案だと思いますし賛成ですが、今は時間がないのでちゃんとゲームとして出来上がったら作りませんか？

2021-12-23 03:43 UTC, suzakutakumi commented on VirusBuster/src/BulletReflect.cpp
> +	if (0 >= Body.x or Body.x >= Scene::Width()) {
わかりました

2021-12-23 03:46 UTC, suzakutakumi commented
BulletSnipeの方で作った関数を、BulletReflectで使用していないので、一回mainブランチに戻ってから生やすべきだと思います

2021-12-23 03:47 UTC, suzakutakumi approved these changes
全体的に良さそうなのでLGTM

2021-12-23 04:02 UTC, id-isymhrk commented
> BulletSnipeの方で作った関数を、BulletReflectで使用していないので、一回mainブランチに戻ってから生やすべきだと思います

確かに関数は使っていなかったんですけど、比較対象が欲しかったのでメインから生やすと消えてしまうのでやはり少し困ります。（個人的に）
ですので、次回からは承認を待っている間に関連性の薄い別の作業をすすめようと思います。

2021-12-23 04:03 UTC, merged